### ISSUE TITLE
Add dependency or documentation mention of django-database-storage

### ISSUE THREAD

**Issue by gene1wood** [mozilla/disk_key_encrypter#1]
Looks like this uses `django-database-storage`, should probably mention it in the README or a setup.py dependency or django dependency list

**Comment by rtucker-mozilla** [comment]
It’s taken care of via the vendor dir

**Comment by rtucker-mozilla** [comment]
I never sent the code upstream. I've done so and the vendor dir is there now. Thanks for catching it

**Comment by gene1wood** [comment]
This was added in #2
